name: $(BuildDefinitionName)_$(SourceBranchName)_$(Year:yyyy).$(Month).$(DayOfMonth)$(Rev:.r)
trigger:
  branches:
    include:
    - develop
pool:
  vmImage: 'ubuntu-latest'
steps:
- task: DockerInstaller@0
  inputs:
    dockerVersion: '18.06.0-ce'
    releaseType: stable
- task: Docker@2
  inputs:
    containerRegistry: 'IMS Docker Hub'
    repository: 'intermecaserv/intermecaserv'
    command: 'buildAndPush'
    Dockerfile: 'IMS.URM/Dockerfile'
    buildContext: '.'
    tags: 'imsurm'
- task: CopyFiles@2
  inputs:
    SourceFolder: './'
    Contents: '**/docker-compose*'
    TargetFolder: '$(Build.ArtifactStagingDirectory)'
    CleanTargetFolder: true
    OverWrite: true
- task: PublishBuildArtifacts@1
  inputs:
    Parallel: true
    PathtoPublish: '$(Build.ArtifactStagingDirectory)'
    ParallelCount: 4
    ArtifactName: 'drop'
    publishLocation: 'Container'
